[2016-08-06 12:06:45,995] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-08-06 12:07:52,565] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:08:00,781] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:08:01,108] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2016-08-06 12:08:01,109] INFO [KafkaApi-0] Auto creation of topic Trump with 1 partitions and replication factor 1 is successful! (kafka.server.KafkaApis)
[2016-08-06 12:08:01,110] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 2 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:08:01,426] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions [Trump,0] (kafka.server.ReplicaFetcherManager)
[2016-08-06 12:08:01,432] INFO Completed load of log Trump-0 with log end offset 0 (kafka.log.Log)
[2016-08-06 12:08:01,433] INFO Created log for partition [Trump,0] in /tmp/kafka-logs with properties {compression.type -> producer, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> true, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> delete, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 3600000, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2016-08-06 12:08:01,434] INFO Partition [Trump,0] on broker 0: No checkpointed highwatermark is found for partition [Trump,0] (kafka.cluster.Partition)
[2016-08-06 12:08:02,415] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 3 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:08:02,417] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 3 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:08:02,419] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 3 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:08:05,527] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 4 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:08:05,529] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 4 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:08:54,244] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:09:32,620] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 4 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:09:35,708] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 5 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:09:35,710] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 5 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:09:35,712] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 5 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:09:39,233] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 6 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:09:39,235] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 6 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:12:27,215] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:12:34,865] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:16:45,976] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-08-06 12:23:01,226] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:23:07,479] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:23:07,748] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 6 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:10,936] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 7 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:10,938] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 7 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:13,944] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 7 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:17,050] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 8 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:17,052] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 8 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:50,124] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 8 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:53,183] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 9 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:53,184] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 9 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:53,186] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 9 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:56,706] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 10 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:23:56,707] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 10 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:25:32,618] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:26:45,957] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-08-06 12:27:46,420] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:27:47,414] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2016-08-06 12:27:47,415] INFO [KafkaApi-0] Auto creation of topic football with 1 partitions and replication factor 1 is successful! (kafka.server.KafkaApis)
[2016-08-06 12:27:47,726] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions [football,0] (kafka.server.ReplicaFetcherManager)
[2016-08-06 12:27:47,732] INFO Completed load of log football-0 with log end offset 0 (kafka.log.Log)
[2016-08-06 12:27:47,732] INFO Created log for partition [football,0] in /tmp/kafka-logs with properties {compression.type -> producer, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> true, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> delete, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 3600000, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2016-08-06 12:27:47,733] INFO Partition [football,0] on broker 0: No checkpointed highwatermark is found for partition [football,0] (kafka.cluster.Partition)
[2016-08-06 12:27:47,946] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2016-08-06 12:27:47,947] INFO [KafkaApi-0] Auto creation of topic Hillary with 1 partitions and replication factor 1 is successful! (kafka.server.KafkaApis)
[2016-08-06 12:27:47,954] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions [Hillary,0] (kafka.server.ReplicaFetcherManager)
[2016-08-06 12:27:47,956] INFO Completed load of log Hillary-0 with log end offset 0 (kafka.log.Log)
[2016-08-06 12:27:47,957] INFO Created log for partition [Hillary,0] in /tmp/kafka-logs with properties {compression.type -> producer, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> true, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> delete, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 3600000, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2016-08-06 12:27:47,957] INFO Partition [Hillary,0] on broker 0: No checkpointed highwatermark is found for partition [Hillary,0] (kafka.cluster.Partition)
[2016-08-06 12:27:48,270] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2016-08-06 12:27:48,271] INFO [KafkaApi-0] Auto creation of topic Pokemon with 1 partitions and replication factor 1 is successful! (kafka.server.KafkaApis)
[2016-08-06 12:27:48,278] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions [Pokemon,0] (kafka.server.ReplicaFetcherManager)
[2016-08-06 12:27:48,280] INFO Completed load of log Pokemon-0 with log end offset 0 (kafka.log.Log)
[2016-08-06 12:27:48,281] INFO Created log for partition [Pokemon,0] in /tmp/kafka-logs with properties {compression.type -> producer, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> true, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> delete, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 3600000, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2016-08-06 12:27:48,281] INFO Partition [Pokemon,0] on broker 0: No checkpointed highwatermark is found for partition [Pokemon,0] (kafka.cluster.Partition)
[2016-08-06 12:27:49,939] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:27:50,008] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2016-08-06 12:27:50,009] INFO [KafkaApi-0] Auto creation of topic Modi with 1 partitions and replication factor 1 is successful! (kafka.server.KafkaApis)
[2016-08-06 12:27:50,014] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions [Modi,0] (kafka.server.ReplicaFetcherManager)
[2016-08-06 12:27:50,016] INFO Completed load of log Modi-0 with log end offset 0 (kafka.log.Log)
[2016-08-06 12:27:50,016] INFO Created log for partition [Modi,0] in /tmp/kafka-logs with properties {compression.type -> producer, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> true, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> delete, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 3600000, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2016-08-06 12:27:50,016] INFO Partition [Modi,0] on broker 0: No checkpointed highwatermark is found for partition [Modi,0] (kafka.cluster.Partition)
[2016-08-06 12:27:50,201] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 10 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:27:51,687] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 11 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:27:51,689] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 11 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:27:54,696] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 11 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:27:55,126] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2016-08-06 12:27:55,127] INFO [KafkaApi-0] Auto creation of topic nba with 1 partitions and replication factor 1 is successful! (kafka.server.KafkaApis)
[2016-08-06 12:27:55,133] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions [nba,0] (kafka.server.ReplicaFetcherManager)
[2016-08-06 12:27:55,135] INFO Completed load of log nba-0 with log end offset 0 (kafka.log.Log)
[2016-08-06 12:27:55,136] INFO Created log for partition [nba,0] in /tmp/kafka-logs with properties {compression.type -> producer, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> true, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> delete, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 3600000, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2016-08-06 12:27:55,137] INFO Partition [nba,0] on broker 0: No checkpointed highwatermark is found for partition [nba,0] (kafka.cluster.Partition)
[2016-08-06 12:27:57,795] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 12 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:27:57,798] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 12 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:28:11,488] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:28:11,756] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 12 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:28:27,802] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 13 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:28:27,804] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 13 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:28:27,806] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 13 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:28:31,327] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 14 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:28:31,329] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 14 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:29:13,605] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 14 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:29:17,086] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 15 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:29:17,088] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 15 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:29:17,090] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 15 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:29:20,605] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 16 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:29:20,607] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 16 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:31:26,664] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:31:28,308] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:31:28,577] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 16 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:31:30,361] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 17 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:31:30,363] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 17 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:31:30,365] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 17 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:32:00,364] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 18 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:32:00,366] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 18 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:32:00,368] INFO [GroupCoordinator 0]: Preparing to restabilize group kafka-python-default-group with old generation 18 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:32:03,886] INFO [GroupCoordinator 0]: Stabilized group kafka-python-default-group generation 19 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:32:03,888] INFO [GroupCoordinator 0]: Assignment received from leader for group kafka-python-default-group for generation 19 (kafka.coordinator.GroupCoordinator)
[2016-08-06 12:32:59,485] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2016-08-06 12:36:45,936] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-08-06 12:46:45,917] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-08-06 12:56:45,899] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
